# Generated by Django 6.1 on 2026-09-13 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
    ]
