# Generated by Django 6.1.1 on 2026-09-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_icon',
            field=models.CharField(blank=True, choices=[('avatar-1', 'Avatar 1'), ('avatar-2', 'Avatar 2')], max_length=30),
        ),
    ]
