# Generated by Django 6.1.1 on 2026-09-28 14:05

from django.db import migrations, models


def verify_existing_users(apps, schema_editor):
    """Accounts that existed before email verification was introduced stay
    usable: give every existing user a profile marked as verified."""
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('habits', 'UserProfile')
    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user, defaults={'email_verified': True})


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('habits', '0006_userprofile_avatar_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.RunPython(verify_existing_users, migrations.RunPython.noop),
    ]
