# Generated by Django 6.1.1 on 2026-09-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_userprofile_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
