"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


PLACEHOLDER_HINTS = ('your-google-ai-studio-key-here', 'your.address@gmail.com',
                     'your16letterapppassword', 'put-a-long-random-string-here')


def _load_dotenv(path):
    """Tiny .env reader (KEY=VALUE per line) so no extra package is needed.

    * utf-8-sig: Windows editors often add a BOM, which would otherwise glue
      itself onto the first variable's name.
    * The values in .env WIN over variables already set in Windows (an old
      GOOGLE_API_KEY set globally used to silently override .env, so editing
      .env seemed to do nothing).
    * Placeholder values copied from .env.example are ignored, with a warning.
    """
    if not path.exists():
        print(f'[settings] WARNING: {path} not found -- copy .env.example to .env')
        return
    for line in path.read_text(encoding='utf-8-sig').splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key == 'EMAIL_HOST_PASSWORD':
            value = value.replace(' ', '')  # Google shows app passwords with spaces
        if not key:
            continue
        if value in PLACEHOLDER_HINTS:
            print(f'[settings] WARNING: {key} in .env is still the example placeholder -- ignoring it')
            continue
        os.environ[key] = value


_load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Set DJANGO_SECRET_KEY in .env / the real environment for any deployment.
# The fallback below is for local development only.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-ym$=)%a+=2!qre0z3y0t)(99-kl*(cbkv9y_9gm^y*ro%1e6)y',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to True for local development; set DJANGO_DEBUG=False in production.
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').strip().lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'habits.apps.HabitsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# "Today" for check-ins/streaks follows this zone. With UTC, users in Egypt
# saw their day roll over at 2-3 AM local time. Override with DJANGO_TIME_ZONE.
TIME_ZONE = os.environ.get('DJANGO_TIME_ZONE', 'Africa/Cairo')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

# User-uploaded files (profile pictures, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Max size for an uploaded profile picture (5 MB)
PROFILE_PICTURE_MAX_BYTES = 5 * 1024 * 1024

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Auth redirects
# https://docs.djangoproject.com/en/6.1/ref/settings/#login-url

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'index'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
#
# Real delivery is configured through a `.env` file next to manage.py (see
# .env.example). If EMAIL_HOST_USER isn't set, emails are printed to the
# terminal instead (handy for development).


EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
    EMAIL_TIMEOUT = 15
    DEFAULT_FROM_EMAIL = f'Habit Tracker <{EMAIL_HOST_USER}>'
else:
    EMAIL_BACKEND = 'habits.console_email.EmailBackend'
    DEFAULT_FROM_EMAIL = 'Habit Tracker <no-reply@habittracker.local>'
